"""Constants used throughout the Pomodoro Timer application."""

# Timer defaults
DEFAULT_DURATION_MINUTES = 25
DEFAULT_DURATION_SECONDS = DEFAULT_DURATION_MINUTES * 60

# Display settings
DEFAULT_FONT_SIZE = 96
WINDOW_PADDING_X = 40
WINDOW_PADDING_Y = 20
TEXT_OFFSET_X = 20
TEXT_OFFSET_Y = -2
TEXT_HEIGHT_ADJUSTMENT = 15

# Window settings
WINDOW_ALPHA = 0.95
DEFAULT_WINDOW_X = 100
DEFAULT_WINDOW_Y = 100

# Movement speeds
MOVE_SPEED_FAST = 50
MOVE_SPEED_SLOW = 5

# Colors
COLOR_TIMER_TEXT = '#00ff00'  # Green
COLOR_BACKGROUND = '#000000'  # Black
COLOR_BORDER_FOCUSED = 'white'
COLOR_TOOLTIP_BG = '#333333'
COLOR_TOOLTIP_FG = 'white'

# Tooltip settings
TOOLTIP_DURATION_MS = 1500
TOOLTIP_FONT_SIZE = 12
TOOLTIP_PADDING_X = 10
TOOLTIP_PADDING_Y = 5
TOOLTIP_OFFSET_Y = 10
TOOLTIP_HEIGHT_ESTIMATE = 40
TOOLTIP_WIDTH_ESTIMATE = 150

# Update intervals
DISPLAY_UPDATE_INTERVAL_MS = 100

# Font settings
DEFAULT_FONT_NAME = 'Arial'
DEFAULT_FONT_FILE = 'arial.ttf'